-- Create Profiles Table
create table public.profiles (
  id uuid references auth.users not null,
  updated_at timestamp with time zone,
  full_name text,
  email text,
  first_name text,
  last_name text,
  bio text,
  primary key (id),
  constraint username_length check (char_length(full_name) >= 3)
);

-- Handle New User trigger
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Create Transactions Table
create table public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  amount numeric not null,
  type text check (type in ('income', 'expense')) not null,
  category text,
  date date not null,
  status text default 'Completed'
);

-- Enable RLS
alter table public.profiles enable row level security;
alter table public.transactions enable row level security;

-- Policies
create policy "Users can view own profile" 
  on profiles for select 
  using ( auth.uid() = id );

-- Updated Policies for RLS Fix
drop policy if exists "Users can update own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;

create policy "Users can insert own profile" 
  on public.profiles for insert 
  with check ( auth.uid() = id );

create policy "Users can update own profile" 
  on public.profiles for update 
  using ( auth.uid() = id )
  with check ( auth.uid() = id );

create policy "Users can view own transactions" 
  on transactions for select 
  using ( auth.uid() = user_id );

create policy "Users can insert own transactions" 
  on transactions for insert 
  with check ( auth.uid() = user_id );

-- Create Subscriptions Table
create table public.subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  price numeric not null,
  cycle text check (cycle in ('Monthly', 'Yearly')) not null,
  next_payment_date date not null
);

alter table public.subscriptions enable row level security;

create policy "Users can view own subscriptions" 
  on subscriptions for select 
  using ( auth.uid() = user_id );

create policy "Users can insert own subscriptions" 
  on subscriptions for insert 
  with check ( auth.uid() = user_id );

create policy "Users can update own subscriptions" 
  on subscriptions for update
  using ( auth.uid() = user_id );

create policy "Users can delete own subscriptions" 
  on subscriptions for delete
  using ( auth.uid() = user_id );

-- Create Budgets Table
create table public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  category text not null,
  limit_amount numeric not null,
  unique(user_id, category)
);

alter table public.budgets enable row level security;

create policy "Users can view own budgets" 
  on budgets for select 
  using ( auth.uid() = user_id );

create policy "Users can insert own budgets" 
  on budgets for insert 
  with check ( auth.uid() = user_id );

create policy "Users can update own budgets" 
  on budgets for update
  using ( auth.uid() = user_id );

create policy "Users can delete own budgets" 
  on budgets for delete
  using ( auth.uid() = user_id );

-- Create Savings Goals Table
create table public.savings_goals (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  target_amount numeric not null,
  current_amount numeric default 0 not null,
  target_date date not null
);

alter table public.savings_goals enable row level security;

create policy "Users can view own savings goals" 
  on savings_goals for select 
  using ( auth.uid() = user_id );

create policy "Users can insert own savings goals" 
  on savings_goals for insert 
  with check ( auth.uid() = user_id );

create policy "Users can update own savings goals" 
  on savings_goals for update
  using ( auth.uid() = user_id );

create policy "Users can delete own savings goals" 
  on savings_goals for delete
  using ( auth.uid() = user_id );

-- Create Bill Splits Table
create table public.bill_splits (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  total_amount numeric not null,
  number_of_people int not null,
  amount_per_person numeric not null,
  status text default 'Pending' check (status in ('Pending', 'Paid'))
);

alter table public.bill_splits enable row level security;

create policy "Users can view own bill splits" 
  on bill_splits for select 
  using ( auth.uid() = user_id );

create policy "Users can insert own bill splits" 
  on bill_splits for insert 
  with check ( auth.uid() = user_id );

create policy "Users can update own bill splits" 
  on bill_splits for update
  using ( auth.uid() = user_id );

create policy "Users can delete own bill splits" 
  on bill_splits for delete
  using ( auth.uid() = user_id );

-- Optimizasyon: Indexler
create index idx_transactions_user_id on public.transactions(user_id);
create index idx_transactions_date on public.transactions(date);




